//! AES-256-GCM utilities for QQBot scan-to-configure credential decryption.
//!
//! Port of `gateway/platforms/qqbot/crypto.py`.
//!
//! The Python implementation uses `cryptography`'s `AESGCM`, where the
//! ciphertext passed to `decrypt` is the concatenation of ciphertext + 16-byte
//! authentication tag. The Rust `aes-gcm` crate's `decrypt` likewise expects
//! the tag appended to the ciphertext, so the wire layout maps directly.

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;

/// Errors that can occur while decrypting a QQBot bind secret.
#[derive(Debug)]
pub enum CryptoError {
    /// Base64 decoding of either the key or the ciphertext failed.
    Base64(String),
    /// The supplied AES key was not exactly 32 bytes (256 bits).
    InvalidKeyLength(usize),
    /// The ciphertext was shorter than the 12-byte IV prefix.
    CiphertextTooShort(usize),
    /// AES-256-GCM authentication / decryption failed.
    Decrypt,
    /// The decrypted plaintext was not valid UTF-8.
    Utf8(std::string::FromUtf8Error),
}

impl std::fmt::Display for CryptoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CryptoError::Base64(e) => write!(f, "base64 decode error: {e}"),
            CryptoError::InvalidKeyLength(n) => {
                write!(f, "invalid AES key length: expected 32 bytes, got {n}")
            }
            CryptoError::CiphertextTooShort(n) => {
                write!(f, "ciphertext too short: need at least 12 bytes, got {n}")
            }
            CryptoError::Decrypt => write!(f, "AES-256-GCM decryption failed"),
            CryptoError::Utf8(e) => write!(f, "plaintext is not valid UTF-8: {e}"),
        }
    }
}

impl std::error::Error for CryptoError {}

/// Generate a 256-bit random AES key and return it as base64.
///
/// The key is passed to `create_bind_task` so the server can encrypt the bot's
/// *client_secret* before returning it. Only this CLI holds the key, ensuring
/// the secret never travels in plaintext.
pub fn generate_bind_key() -> String {
    let mut key = [0u8; 32];
    getrandom::fill(&mut key).expect("failed to read OS randomness for AES key");
    B64.encode(key)
}

/// Decrypt a base64-encoded AES-256-GCM ciphertext.
///
/// Ciphertext layout (after base64-decoding):
///
/// ```text
/// IV (12 bytes) ‖ ciphertext (N bytes) ‖ AuthTag (16 bytes)
/// ```
///
/// * `encrypted_base64` is the `bot_encrypt_secret` value from
///   `poll_bind_result`.
/// * `key_base64` is the base64 AES key generated by [`generate_bind_key`].
///
/// Returns the decrypted *client_secret* as a UTF-8 string.
pub fn decrypt_secret(encrypted_base64: &str, key_base64: &str) -> Result<String, CryptoError> {
    let key_bytes = B64
        .decode(key_base64.trim())
        .map_err(|e| CryptoError::Base64(e.to_string()))?;
    if key_bytes.len() != 32 {
        return Err(CryptoError::InvalidKeyLength(key_bytes.len()));
    }

    let raw = B64
        .decode(encrypted_base64.trim())
        .map_err(|e| CryptoError::Base64(e.to_string()))?;
    if raw.len() < 12 {
        return Err(CryptoError::CiphertextTooShort(raw.len()));
    }

    let (iv, ciphertext_with_tag) = raw.split_at(12);

    let key = Key::<Aes256Gcm>::from_slice(&key_bytes);
    let cipher = Aes256Gcm::new(key);
    let nonce = Nonce::from_slice(iv);

    // No associated data, mirroring the Python `None` AAD argument.
    let plaintext = cipher
        .decrypt(nonce, ciphertext_with_tag)
        .map_err(|_| CryptoError::Decrypt)?;

    String::from_utf8(plaintext).map_err(CryptoError::Utf8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use aes_gcm::aead::{Aead, KeyInit};
    use aes_gcm::{Aes256Gcm, Key, Nonce};

    /// Helper that mirrors the server side: encrypt with AES-256-GCM and
    /// produce `base64(IV ‖ ciphertext ‖ tag)`.
    fn encrypt(plaintext: &[u8], key_bytes: &[u8; 32], iv: &[u8; 12]) -> String {
        let key = Key::<Aes256Gcm>::from_slice(key_bytes);
        let cipher = Aes256Gcm::new(key);
        let nonce = Nonce::from_slice(iv);
        let ct = cipher.encrypt(nonce, plaintext).unwrap();
        let mut raw = Vec::with_capacity(12 + ct.len());
        raw.extend_from_slice(iv);
        raw.extend_from_slice(&ct);
        B64.encode(raw)
    }

    #[test]
    fn generate_bind_key_is_32_bytes_base64() {
        let k = generate_bind_key();
        let decoded = B64.decode(&k).expect("valid base64");
        assert_eq!(decoded.len(), 32);
    }

    #[test]
    fn generate_bind_key_is_random() {
        assert_ne!(generate_bind_key(), generate_bind_key());
    }

    #[test]
    fn roundtrip_decrypt() {
        let key_bytes = [7u8; 32];
        let iv = [3u8; 12];
        let secret = "super-secret-client-secret-value";
        let enc = encrypt(secret.as_bytes(), &key_bytes, &iv);
        let key_b64 = B64.encode(key_bytes);

        let out = decrypt_secret(&enc, &key_b64).expect("decrypt ok");
        assert_eq!(out, secret);
    }

    #[test]
    fn roundtrip_with_generated_key() {
        let key_b64 = generate_bind_key();
        let key_bytes: [u8; 32] = B64.decode(&key_b64).unwrap().try_into().unwrap();
        let iv = [42u8; 12];
        let secret = "another value";
        let enc = encrypt(secret.as_bytes(), &key_bytes, &iv);

        assert_eq!(decrypt_secret(&enc, &key_b64).unwrap(), secret);
    }

    #[test]
    fn wrong_key_fails_auth() {
        let key_bytes = [7u8; 32];
        let iv = [3u8; 12];
        let enc = encrypt(b"hello", &key_bytes, &iv);

        let wrong = B64.encode([8u8; 32]);
        assert!(matches!(
            decrypt_secret(&enc, &wrong),
            Err(CryptoError::Decrypt)
        ));
    }

    #[test]
    fn invalid_key_length_rejected() {
        let short_key = B64.encode([1u8; 16]);
        assert!(matches!(
            decrypt_secret("AAAAAAAAAAAAAAAA", &short_key),
            Err(CryptoError::InvalidKeyLength(16))
        ));
    }

    #[test]
    fn ciphertext_too_short_rejected() {
        let key = B64.encode([1u8; 32]);
        // 4 raw bytes after base64 decode -> shorter than the 12-byte IV.
        let short_ct = B64.encode([0u8; 4]);
        assert!(matches!(
            decrypt_secret(&short_ct, &key),
            Err(CryptoError::CiphertextTooShort(4))
        ));
    }

    #[test]
    fn bad_base64_key_rejected() {
        assert!(matches!(
            decrypt_secret("AAAA", "!!!not base64!!!"),
            Err(CryptoError::Base64(_))
        ));
    }
}
