// @generated by scripts/gen_skins.py from hermes_cli/skin_engine.py
// Do not edit by hand. Re-run the generator when _BUILTIN_SKINS changes.
//
// Built-in skin definitions (colors/branding/banner art). The skin
// resolution logic lives in skins.rs and mirrors hermes_cli/skin_engine.py.
// Note: spinner and tool_emojis fields are intentionally omitted — the
// resolve_skin() payload consumed by the TUI gateway does not include them.

use super::skins::BuiltinSkin;

pub(super) const BUILTIN_SKINS: &[BuiltinSkin] = &[
    BuiltinSkin {
        key: "default",
        name: "default",
        description: "Classic Hermes — gold and kawaii",
        colors: &[("banner_border", "#CD7F32"), ("banner_title", "#FFD700"), ("banner_accent", "#FFBF00"), ("banner_dim", "#B8860B"), ("banner_text", "#FFF8DC"), ("ui_accent", "#FFBF00"), ("ui_label", "#DAA520"), ("ui_ok", "#4caf50"), ("ui_error", "#ef5350"), ("ui_warn", "#ffa726"), ("prompt", "#FFF8DC"), ("input_rule", "#CD7F32"), ("response_border", "#FFD700"), ("status_bar_bg", "#1a1a2e"), ("session_label", "#DAA520"), ("session_border", "#8B8682")],
        branding: &[("agent_name", "Hermes Agent"), ("welcome", "Welcome to Hermes Agent! Type your message or /help for commands."), ("goodbye", "Goodbye! ⚕"), ("response_label", " ⚕ Hermes "), ("prompt_symbol", "❯"), ("help_header", "(^_^)? Available Commands")],
        tool_prefix: "┊",
        banner_logo: "",
        banner_hero: "",
    },
    BuiltinSkin {
        key: "ares",
        name: "ares",
        description: "War-god theme — crimson and bronze",
        colors: &[("banner_border", "#9F1C1C"), ("banner_title", "#C7A96B"), ("banner_accent", "#DD4A3A"), ("banner_dim", "#6B1717"), ("banner_text", "#F1E6CF"), ("ui_accent", "#DD4A3A"), ("ui_label", "#C7A96B"), ("ui_ok", "#4caf50"), ("ui_error", "#ef5350"), ("ui_warn", "#ffa726"), ("prompt", "#F1E6CF"), ("input_rule", "#9F1C1C"), ("response_border", "#C7A96B"), ("status_bar_bg", "#2A1212"), ("status_bar_text", "#F1E6CF"), ("status_bar_strong", "#C7A96B"), ("status_bar_dim", "#6E584B"), ("status_bar_good", "#7BC96F"), ("status_bar_warn", "#C7A96B"), ("status_bar_bad", "#DD4A3A"), ("status_bar_critical", "#EF5350"), ("session_label", "#C7A96B"), ("session_border", "#6E584B")],
        branding: &[("agent_name", "Ares Agent"), ("welcome", "Welcome to Ares Agent! Type your message or /help for commands."), ("goodbye", "Farewell, warrior! ⚔"), ("response_label", " ⚔ Ares "), ("prompt_symbol", "⚔"), ("help_header", "(⚔) Available Commands")],
        tool_prefix: "╎",
        banner_logo: "[bold #A3261F] █████╗ ██████╗ ███████╗███████╗       █████╗  ██████╗ ███████╗███╗   ██╗████████╗[/]\n[bold #B73122]██╔══██╗██╔══██╗██╔════╝██╔════╝      ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝[/]\n[#C93C24]███████║██████╔╝█████╗  ███████╗█████╗███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║[/]\n[#D84A28]██╔══██║██╔══██╗██╔══╝  ╚════██║╚════╝██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║[/]\n[#E15A2D]██║  ██║██║  ██║███████╗███████║      ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║[/]\n[#EB6C32]╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝      ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝[/]",
        banner_hero: "[#9F1C1C]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#9F1C1C]⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⠟⠻⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#C7A96B]⠀⠀⠀⠀⠀⠀⠀⣠⣾⡿⠋⠀⠀⠀⠙⢿⣷⣄⠀⠀⠀⠀⠀⠀⠀[/]\n[#C7A96B]⠀⠀⠀⠀⠀⢀⣾⡿⠋⠀⠀⢠⡄⠀⠀⠙⢿⣷⡀⠀⠀⠀⠀⠀[/]\n[#DD4A3A]⠀⠀⠀⠀⣰⣿⠟⠀⠀⠀⣰⣿⣿⣆⠀⠀⠀⠻⣿⣆⠀⠀⠀⠀[/]\n[#DD4A3A]⠀⠀⠀⢰⣿⠏⠀⠀⢀⣾⡿⠉⢿⣷⡀⠀⠀⠹⣿⡆⠀⠀⠀[/]\n[#9F1C1C]⠀⠀⠀⣿⡟⠀⠀⣠⣿⠟⠀⠀⠀⠻⣿⣄⠀⠀⢻⣿⠀⠀⠀[/]\n[#9F1C1C]⠀⠀⠀⣿⡇⠀⠀⠙⠋⠀⠀⚔⠀⠀⠙⠋⠀⠀⢸⣿⠀⠀⠀[/]\n[#6B1717]⠀⠀⠀⢿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡿⠀⠀⠀[/]\n[#6B1717]⠀⠀⠀⠘⢿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⡿⠃⠀⠀⠀[/]\n[#C7A96B]⠀⠀⠀⠀⠈⠻⣿⣷⣦⣤⣀⣀⣤⣤⣶⣿⠿⠋⠀⠀⠀⠀[/]\n[#C7A96B]⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⠿⠿⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀[/]\n[#DD4A3A]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⚔⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[dim #6B1717]⠀⠀⠀⠀⠀⠀⠀⠀war god online⠀⠀⠀⠀⠀⠀⠀⠀[/]",
    },
    BuiltinSkin {
        key: "mono",
        name: "mono",
        description: "Monochrome — clean grayscale",
        colors: &[("banner_border", "#555555"), ("banner_title", "#e6edf3"), ("banner_accent", "#aaaaaa"), ("banner_dim", "#444444"), ("banner_text", "#c9d1d9"), ("ui_accent", "#aaaaaa"), ("ui_label", "#888888"), ("ui_ok", "#888888"), ("ui_error", "#cccccc"), ("ui_warn", "#999999"), ("prompt", "#c9d1d9"), ("input_rule", "#444444"), ("response_border", "#aaaaaa"), ("status_bar_bg", "#1F1F1F"), ("status_bar_text", "#C9D1D9"), ("status_bar_strong", "#E6EDF3"), ("status_bar_dim", "#777777"), ("status_bar_good", "#B5B5B5"), ("status_bar_warn", "#AAAAAA"), ("status_bar_bad", "#D0D0D0"), ("status_bar_critical", "#F0F0F0"), ("session_label", "#888888"), ("session_border", "#555555")],
        branding: &[("agent_name", "Hermes Agent"), ("welcome", "Welcome to Hermes Agent! Type your message or /help for commands."), ("goodbye", "Goodbye! ⚕"), ("response_label", " ⚕ Hermes "), ("prompt_symbol", "❯"), ("help_header", "[?] Available Commands")],
        tool_prefix: "┊",
        banner_logo: "",
        banner_hero: "",
    },
    BuiltinSkin {
        key: "slate",
        name: "slate",
        description: "Cool blue — developer-focused",
        colors: &[("banner_border", "#4169e1"), ("banner_title", "#7eb8f6"), ("banner_accent", "#8EA8FF"), ("banner_dim", "#4b5563"), ("banner_text", "#c9d1d9"), ("ui_accent", "#7eb8f6"), ("ui_label", "#8EA8FF"), ("ui_ok", "#63D0A6"), ("ui_error", "#F7A072"), ("ui_warn", "#e6a855"), ("prompt", "#c9d1d9"), ("input_rule", "#4169e1"), ("response_border", "#7eb8f6"), ("status_bar_bg", "#151C2F"), ("status_bar_text", "#C9D1D9"), ("status_bar_strong", "#7EB8F6"), ("status_bar_dim", "#4B5563"), ("status_bar_good", "#63D0A6"), ("status_bar_warn", "#E6A855"), ("status_bar_bad", "#F7A072"), ("status_bar_critical", "#FF7A7A"), ("session_label", "#7eb8f6"), ("session_border", "#4b5563")],
        branding: &[("agent_name", "Hermes Agent"), ("welcome", "Welcome to Hermes Agent! Type your message or /help for commands."), ("goodbye", "Goodbye! ⚕"), ("response_label", " ⚕ Hermes "), ("prompt_symbol", "❯"), ("help_header", "(^_^)? Available Commands")],
        tool_prefix: "┊",
        banner_logo: "",
        banner_hero: "",
    },
    BuiltinSkin {
        key: "daylight",
        name: "daylight",
        description: "Light theme for bright terminals with dark text and cool blue accents",
        colors: &[("banner_border", "#2563EB"), ("banner_title", "#0F172A"), ("banner_accent", "#1D4ED8"), ("banner_dim", "#475569"), ("banner_text", "#111827"), ("ui_accent", "#2563EB"), ("ui_label", "#0F766E"), ("ui_ok", "#15803D"), ("ui_error", "#B91C1C"), ("ui_warn", "#B45309"), ("prompt", "#111827"), ("input_rule", "#93C5FD"), ("response_border", "#2563EB"), ("session_label", "#1D4ED8"), ("session_border", "#64748B"), ("status_bar_bg", "#E5EDF8"), ("voice_status_bg", "#E5EDF8"), ("completion_menu_bg", "#F8FAFC"), ("completion_menu_current_bg", "#DBEAFE"), ("completion_menu_meta_bg", "#EEF2FF"), ("completion_menu_meta_current_bg", "#BFDBFE")],
        branding: &[("agent_name", "Hermes Agent"), ("welcome", "Welcome to Hermes Agent! Type your message or /help for commands."), ("goodbye", "Goodbye! ⚕"), ("response_label", " ⚕ Hermes "), ("prompt_symbol", "❯"), ("help_header", "[?] Available Commands")],
        tool_prefix: "│",
        banner_logo: "",
        banner_hero: "",
    },
    BuiltinSkin {
        key: "warm-lightmode",
        name: "warm-lightmode",
        description: "Warm light mode — dark brown/gold text for light terminal backgrounds",
        colors: &[("banner_border", "#8B6914"), ("banner_title", "#5C3D11"), ("banner_accent", "#8B4513"), ("banner_dim", "#8B7355"), ("banner_text", "#2C1810"), ("ui_accent", "#8B4513"), ("ui_label", "#5C3D11"), ("ui_ok", "#2E7D32"), ("ui_error", "#C62828"), ("ui_warn", "#E65100"), ("prompt", "#2C1810"), ("input_rule", "#8B6914"), ("response_border", "#8B6914"), ("session_label", "#5C3D11"), ("session_border", "#A0845C"), ("status_bar_bg", "#F5F0E8"), ("voice_status_bg", "#F5F0E8"), ("completion_menu_bg", "#F5EFE0"), ("completion_menu_current_bg", "#E8DCC8"), ("completion_menu_meta_bg", "#F0E8D8"), ("completion_menu_meta_current_bg", "#DFCFB0")],
        branding: &[("agent_name", "Hermes Agent"), ("welcome", "Welcome to Hermes Agent! Type your message or /help for commands."), ("goodbye", "Goodbye! ⚕"), ("response_label", " ⚕ Hermes "), ("prompt_symbol", "❯"), ("help_header", "(^_^)? Available Commands")],
        tool_prefix: "┊",
        banner_logo: "",
        banner_hero: "",
    },
    BuiltinSkin {
        key: "poseidon",
        name: "poseidon",
        description: "Ocean-god theme — deep blue and seafoam",
        colors: &[("banner_border", "#2A6FB9"), ("banner_title", "#A9DFFF"), ("banner_accent", "#5DB8F5"), ("banner_dim", "#153C73"), ("banner_text", "#EAF7FF"), ("ui_accent", "#5DB8F5"), ("ui_label", "#A9DFFF"), ("ui_ok", "#4caf50"), ("ui_error", "#ef5350"), ("ui_warn", "#ffa726"), ("prompt", "#EAF7FF"), ("input_rule", "#2A6FB9"), ("response_border", "#5DB8F5"), ("status_bar_bg", "#0F2440"), ("status_bar_text", "#EAF7FF"), ("status_bar_strong", "#A9DFFF"), ("status_bar_dim", "#496884"), ("status_bar_good", "#6ED7B0"), ("status_bar_warn", "#5DB8F5"), ("status_bar_bad", "#2A6FB9"), ("status_bar_critical", "#D94F4F"), ("session_label", "#A9DFFF"), ("session_border", "#496884")],
        branding: &[("agent_name", "Poseidon Agent"), ("welcome", "Welcome to Poseidon Agent! Type your message or /help for commands."), ("goodbye", "Fair winds! Ψ"), ("response_label", " Ψ Poseidon "), ("prompt_symbol", "Ψ"), ("help_header", "(Ψ) Available Commands")],
        tool_prefix: "│",
        banner_logo: "[bold #B8E8FF]██████╗  ██████╗ ███████╗███████╗██╗██████╗  ██████╗ ███╗   ██╗       █████╗  ██████╗ ███████╗███╗   ██╗████████╗[/]\n[bold #97D6FF]██╔══██╗██╔═══██╗██╔════╝██╔════╝██║██╔══██╗██╔═══██╗████╗  ██║      ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝[/]\n[#75C1F6]██████╔╝██║   ██║███████╗█████╗  ██║██║  ██║██║   ██║██╔██╗ ██║█████╗███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║[/]\n[#4FA2E0]██╔═══╝ ██║   ██║╚════██║██╔══╝  ██║██║  ██║██║   ██║██║╚██╗██║╚════╝██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║[/]\n[#2E7CC7]██║     ╚██████╔╝███████║███████╗██║██████╔╝╚██████╔╝██║ ╚████║      ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║[/]\n[#1B4F95]╚═╝      ╚═════╝ ╚══════╝╚══════╝╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═══╝      ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝[/]",
        banner_hero: "[#2A6FB9]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#5DB8F5]⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#5DB8F5]⠀⠀⠀⠀⠀⠀⠀⢠⣿⠏⠀Ψ⠀⠹⣿⡄⠀⠀⠀⠀⠀⠀⠀[/]\n[#A9DFFF]⠀⠀⠀⠀⠀⠀⠀⣿⡟⠀⠀⠀⠀⠀⢻⣿⠀⠀⠀⠀⠀⠀⠀[/]\n[#A9DFFF]⠀⠀⠀≈≈≈≈≈⣿⡇⠀⠀⠀⠀⠀⢸⣿≈≈≈≈≈⠀⠀⠀[/]\n[#5DB8F5]⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀[/]\n[#2A6FB9]⠀⠀⠀⠀⠀⠀⠀⢿⣧⠀⠀⠀⠀⠀⣼⡿⠀⠀⠀⠀⠀⠀⠀[/]\n[#2A6FB9]⠀⠀⠀⠀⠀⠀⠀⠘⢿⣷⣄⣀⣠⣾⡿⠃⠀⠀⠀⠀⠀⠀⠀[/]\n[#153C73]⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#153C73]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#5DB8F5]⠀⠀⠀⠀⠀≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈⠀⠀⠀⠀⠀[/]\n[#A9DFFF]⠀⠀⠀⠀⠀⠀≈≈≈≈≈≈≈≈≈≈≈≈≈⠀⠀⠀⠀⠀⠀[/]\n[dim #153C73]⠀⠀⠀⠀⠀⠀⠀deep waters hold⠀⠀⠀⠀⠀⠀⠀[/]",
    },
    BuiltinSkin {
        key: "sisyphus",
        name: "sisyphus",
        description: "Sisyphean theme — austere grayscale with persistence",
        colors: &[("banner_border", "#B7B7B7"), ("banner_title", "#F5F5F5"), ("banner_accent", "#E7E7E7"), ("banner_dim", "#4A4A4A"), ("banner_text", "#D3D3D3"), ("ui_accent", "#E7E7E7"), ("ui_label", "#D3D3D3"), ("ui_ok", "#919191"), ("ui_error", "#E7E7E7"), ("ui_warn", "#B7B7B7"), ("prompt", "#F5F5F5"), ("input_rule", "#656565"), ("response_border", "#B7B7B7"), ("status_bar_bg", "#202020"), ("status_bar_text", "#D3D3D3"), ("status_bar_strong", "#F5F5F5"), ("status_bar_dim", "#656565"), ("status_bar_good", "#B7B7B7"), ("status_bar_warn", "#D3D3D3"), ("status_bar_bad", "#E7E7E7"), ("status_bar_critical", "#F5F5F5"), ("session_label", "#919191"), ("session_border", "#656565")],
        branding: &[("agent_name", "Sisyphus Agent"), ("welcome", "Welcome to Sisyphus Agent! Type your message or /help for commands."), ("goodbye", "The boulder waits. ◉"), ("response_label", " ◉ Sisyphus "), ("prompt_symbol", "◉"), ("help_header", "(◉) Available Commands")],
        tool_prefix: "│",
        banner_logo: "[bold #F5F5F5]███████╗██╗███████╗██╗   ██╗██████╗ ██╗  ██╗██╗   ██╗███████╗       █████╗  ██████╗ ███████╗███╗   ██╗████████╗[/]\n[bold #E7E7E7]██╔════╝██║██╔════╝╚██╗ ██╔╝██╔══██╗██║  ██║██║   ██║██╔════╝      ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝[/]\n[#D7D7D7]███████╗██║███████╗ ╚████╔╝ ██████╔╝███████║██║   ██║███████╗█████╗███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║[/]\n[#BFBFBF]╚════██║██║╚════██║  ╚██╔╝  ██╔═══╝ ██╔══██║██║   ██║╚════██║╚════╝██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║[/]\n[#8F8F8F]███████║██║███████║   ██║   ██║     ██║  ██║╚██████╔╝███████║      ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║[/]\n[#626262]╚══════╝╚═╝╚══════╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝      ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝[/]",
        banner_hero: "[#B7B7B7]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#D3D3D3]⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#E7E7E7]⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀[/]\n[#F5F5F5]⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀[/]\n[#E7E7E7]⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀[/]\n[#D3D3D3]⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣿⣿⡿⠃⠀⠀⠀⠀⠀⠀⠀[/]\n[#B7B7B7]⠀⠀⠀⠀⠀⠀⠀⠀⠙⠿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#919191]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#656565]⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#656565]⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#4A4A4A]⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#4A4A4A]⠀⠀⠀⠀⠀⣀⣴⣿⣿⣿⣿⣿⣿⣦⣀⠀⠀⠀⠀⠀⠀[/]\n[#656565]⠀⠀⠀━━━━━━━━━━━━━━━━━━━━━━━⠀⠀⠀[/]\n[dim #4A4A4A]⠀⠀⠀⠀⠀⠀⠀⠀⠀the boulder⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]",
    },
    BuiltinSkin {
        key: "charizard",
        name: "charizard",
        description: "Volcanic theme — burnt orange and ember",
        colors: &[("banner_border", "#C75B1D"), ("banner_title", "#FFD39A"), ("banner_accent", "#F29C38"), ("banner_dim", "#7A3511"), ("banner_text", "#FFF0D4"), ("ui_accent", "#F29C38"), ("ui_label", "#FFD39A"), ("ui_ok", "#4caf50"), ("ui_error", "#ef5350"), ("ui_warn", "#ffa726"), ("prompt", "#FFF0D4"), ("input_rule", "#C75B1D"), ("response_border", "#F29C38"), ("status_bar_bg", "#2B160E"), ("status_bar_text", "#FFF0D4"), ("status_bar_strong", "#FFD39A"), ("status_bar_dim", "#6C4724"), ("status_bar_good", "#6BCB77"), ("status_bar_warn", "#F29C38"), ("status_bar_bad", "#E2832B"), ("status_bar_critical", "#EF5350"), ("session_label", "#FFD39A"), ("session_border", "#6C4724")],
        branding: &[("agent_name", "Charizard Agent"), ("welcome", "Welcome to Charizard Agent! Type your message or /help for commands."), ("goodbye", "Flame out! ✦"), ("response_label", " ✦ Charizard "), ("prompt_symbol", "✦"), ("help_header", "(✦) Available Commands")],
        tool_prefix: "│",
        banner_logo: "[bold #FFF0D4] ██████╗██╗  ██╗ █████╗ ██████╗ ██╗███████╗ █████╗ ██████╗ ██████╗        █████╗  ██████╗ ███████╗███╗   ██╗████████╗[/]\n[bold #FFD39A]██╔════╝██║  ██║██╔══██╗██╔══██╗██║╚══███╔╝██╔══██╗██╔══██╗██╔══██╗      ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝[/]\n[#F29C38]██║     ███████║███████║██████╔╝██║  ███╔╝ ███████║██████╔╝██║  ██║█████╗███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║[/]\n[#E2832B]██║     ██╔══██║██╔══██║██╔══██╗██║ ███╔╝  ██╔══██║██╔══██╗██║  ██║╚════╝██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║[/]\n[#C75B1D]╚██████╗██║  ██║██║  ██║██║  ██║██║███████╗██║  ██║██║  ██║██████╔╝      ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║[/]\n[#7A3511] ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝       ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝[/]",
        banner_hero: "[#FFD39A]⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⠶⠶⠶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#F29C38]⠀⠀⠀⠀⠀⠀⣴⠟⠁⠀⠀⠀⠀⠈⠻⣦⠀⠀⠀⠀⠀⠀[/]\n[#F29C38]⠀⠀⠀⠀⠀⣼⠏⠀⠀⠀✦⠀⠀⠀⠀⠹⣧⠀⠀⠀⠀⠀[/]\n[#E2832B]⠀⠀⠀⠀⢰⡟⠀⠀⣀⣤⣤⣤⣀⠀⠀⠀⢻⡆⠀⠀⠀⠀[/]\n[#E2832B]⠀⠀⣠⡾⠛⠁⣠⣾⠟⠉⠀⠉⠻⣷⣄⠀⠈⠛⢷⣄⠀⠀[/]\n[#C75B1D]⠀⣼⠟⠀⢀⣾⠟⠁⠀⠀⠀⠀⠀⠈⠻⣷⡀⠀⠻⣧⠀[/]\n[#C75B1D]⢸⡟⠀⠀⣿⡟⠀⠀⠀🔥⠀⠀⠀⠀⢻⣿⠀⠀⢻⡇[/]\n[#7A3511]⠀⠻⣦⡀⠘⢿⣧⡀⠀⠀⠀⠀⠀⢀⣼⡿⠃⢀⣴⠟⠀[/]\n[#7A3511]⠀⠀⠈⠻⣦⣀⠙⢿⣷⣤⣤⣤⣾⡿⠋⣀⣴⠟⠁⠀⠀[/]\n[#C75B1D]⠀⠀⠀⠀⠈⠙⠛⠶⠤⠭⠭⠤⠶⠛⠋⠁⠀⠀⠀⠀[/]\n[#F29C38]⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#F29C38]⠀⠀⠀⠀⠀⠀⠀⣼⡟⠀⠀⢻⣧⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[dim #7A3511]⠀⠀⠀⠀⠀⠀⠀tail flame lit⠀⠀⠀⠀⠀⠀⠀⠀[/]",
    },
];
