[package]
name = "hermes-rs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
ctrlc.workspace = true
hermes-core = { path = "../hermes-core" }
libc.workspace = true
log.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[[bin]]
name = "hermes"
path = "src/main.rs"
