#!/usr/bin/env python3
"""Generate the native Rust built-in skin table from hermes_cli/skin_engine.py.

Parses the `_BUILTIN_SKINS` dict literal with the stdlib `ast` module (no
imports of hermes_cli are executed) and emits committed Rust at
crates/hermes-core/src/skins_data.rs. The resolution logic (merge-over-default,
user YAML skins, resolve_skin payload) lives in hand-written Rust in skins.rs
and mirrors hermes_cli/skin_engine.py.

Re-run whenever _BUILTIN_SKINS changes:

    python3 scripts/gen_skins.py
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "hermes_cli" / "skin_engine.py"
OUT = REPO / "crates" / "hermes-core" / "src" / "skins_data.rs"


def find_builtin_skins(tree: ast.Module) -> ast.Dict:
    for stmt in tree.body:
        target_names = []
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            target_names = [stmt.target.id]
            value = stmt.value
        elif isinstance(stmt, ast.Assign):
            target_names = [t.id for t in stmt.targets if isinstance(t, ast.Name)]
            value = stmt.value
        else:
            continue
        if "_BUILTIN_SKINS" in target_names and isinstance(value, ast.Dict):
            return value
    raise SystemExit("could not locate _BUILTIN_SKINS dict literal")


def lit(node: ast.AST):
    """Evaluate a literal node into Python data (str/list/dict/bool/num)."""
    return ast.literal_eval(node)


def rust_str(value: str) -> str:
    # Use a raw-ish escape that is always valid in a normal Rust string.
    escaped = (
        value.replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def rust_pairs(d: dict) -> str:
    """Render a dict[str,str] as a Rust slice of (&str,&str) pairs."""
    if not d:
        return "&[]"
    items = ", ".join(f"({rust_str(str(k))}, {rust_str(str(v))})" for k, v in d.items())
    return f"&[{items}]"


def main() -> int:
    tree = ast.parse(SRC.read_text(encoding="utf-8"), filename=str(SRC))
    skins_dict = find_builtin_skins(tree)

    rows = []
    for key_node, value_node in zip(skins_dict.keys, skins_dict.values):
        key = lit(key_node)
        data = lit(value_node)
        colors = {str(k): str(v) for k, v in (data.get("colors") or {}).items()}
        branding = {str(k): str(v) for k, v in (data.get("branding") or {}).items()}
        rows.append(
            "    BuiltinSkin {\n"
            f"        key: {rust_str(str(key))},\n"
            f"        name: {rust_str(str(data.get('name', key)))},\n"
            f"        description: {rust_str(str(data.get('description', '')))},\n"
            f"        colors: {rust_pairs(colors)},\n"
            f"        branding: {rust_pairs(branding)},\n"
            f"        tool_prefix: {rust_str(str(data.get('tool_prefix', '┊')))},\n"
            f"        banner_logo: {rust_str(str(data.get('banner_logo', '')))},\n"
            f"        banner_hero: {rust_str(str(data.get('banner_hero', '')))},\n"
            "    },"
        )

    body = "\n".join(rows)
    out = (
        "// @generated by scripts/gen_skins.py from hermes_cli/skin_engine.py\n"
        "// Do not edit by hand. Re-run the generator when _BUILTIN_SKINS changes.\n"
        "//\n"
        "// Built-in skin definitions (colors/branding/banner art). The skin\n"
        "// resolution logic lives in skins.rs and mirrors hermes_cli/skin_engine.py.\n"
        "// Note: spinner and tool_emojis fields are intentionally omitted — the\n"
        "// resolve_skin() payload consumed by the TUI gateway does not include them.\n\n"
        "use super::skins::BuiltinSkin;\n\n"
        f"pub(super) const BUILTIN_SKINS: &[BuiltinSkin] = &[\n{body}\n];\n"
    )
    OUT.write_text(out, encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} skins)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
